#:schema node_modules/wrangler/config-schema.json
name = "cf-metrics"
tail_consumers = [{service = "cf-metrics-tail"}]
main = "index.js"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
send_metrics = false

[vars]
INFLUX_URL = "http://localhost:8086"
INFLUX_TOKEN = "example"
INFLUX_DATABASE = "example"